In [1]:
import numpy as np
np.random.seed(0)

import random
random.seed(0)

In [2]:
MAX_LEN = 20
MAX_EACH = MAX_LEN // 2
NUM_DATA = 5000

In [3]:
def make_str(existing, a='a', b='b'):
    randstr = None
    while randstr is None or randstr in existing:
        num = random.randrange(MAX_EACH)
        letters = list(a * num + b * num)
        random.shuffle(letters)
        randstr = ''.join(letters)
    return randstr

In [4]:
existing = set()
for _ in range(NUM_DATA):
    existing.add(make_str(existing))

In [5]:
data = []

In [6]:
for y in existing:
    data.append((np.random.rand(4), y))

In [8]:
data

[(array([0.5488135 , 0.71518937, 0.60276338, 0.54488318]), ''),
 (array([0.4236548 , 0.64589411, 0.43758721, 0.891773  ]), 'aabbbaaabbaabb'),
 (array([0.96366276, 0.38344152, 0.79172504, 0.52889492]), 'aaabbabaabbb'),
 (array([0.56804456, 0.92559664, 0.07103606, 0.0871293 ]), 'bbabaaabbaba'),
 (array([0.0202184 , 0.83261985, 0.77815675, 0.87001215]), 'abbbabaaaabb'),
 (array([0.97861834, 0.79915856, 0.46147936, 0.78052918]),
  'bbbabababaaaabaabb'),
 (array([0.11827443, 0.63992102, 0.14335329, 0.94466892]), 'bbbabaaaaabababb'),
 (array([0.52184832, 0.41466194, 0.26455561, 0.77423369]), 'babbabaaab'),
 (array([0.45615033, 0.56843395, 0.0187898 , 0.6176355 ]), 'aabaababbabbbbaa'),
 (array([0.61209572, 0.616934  , 0.94374808, 0.6818203 ]), 'ababaaabbbaabb'),
 (array([0.3595079 , 0.43703195, 0.6976312 , 0.06022547]), 'babababbaa'),
 (array([0.66676672, 0.67063787, 0.21038256, 0.1289263 ]),
  'abbaabaaaaabbabbbb'),
 (array([0.31542835, 0.36371077, 0.57019677, 0.43860151]), 'abaabbbaaabbab')

In [7]:
import pickle

with open('train.pkl', 'wb') as file_out:
    pickle.dump(data, file_out)