In [1]:
import os,sys,inspect
import json
import torch
currentdir = os.path.dirname(os.getcwd())
print(currentdir)
# parent_dir = os.path.abspath(os.path.join(currentdir, os.pardir))
root = os.path.dirname(currentdir)
print("root Folder Absoloute path: ", root)


import sys
sys.path.append(root)

import logging

logging.basicConfig(level=logging.INFO)

from IPython.display import Image

import __main__

__main__.__file__="main.py"

/home/hfaghihi/Framework/new/DomiKnowS/examples
root Folder Absoloute path:  /home/hfaghihi/Framework/new/DomiKnowS


In [2]:
from regr.data.reader import RegrReader
import torch


class SudokuReader(RegrReader):
    def parse_file(self):
        return [["random"] * 1]
    def getidval(self, item):
        return [1]
    def getwhole_sudokuval(self, item):
        base  = 3
        side  = base*base

        # pattern for a baseline valid solution
        def pattern(r,c): return (base*(r%base)+r//base+c)%side

        # randomize rows, columns and numbers (of valid base pattern)
        from random import sample
        def shuffle(s): return sample(s,len(s)) 
        rBase = range(base) 
        rows  = [ g*base + r for g in shuffle(rBase) for r in shuffle(rBase) ] 
        cols  = [ g*base + c for g in shuffle(rBase) for c in shuffle(rBase) ]
        nums  = shuffle(range(1,base*base+1))

        # produce board using randomized baseline pattern
        board = [ [nums[pattern(r,c)] for c in cols] for r in rows ]
        squares = side*side
        empties = squares * 3//4
        for p in sample(range(squares),empties):
            board[p//side][p%side] = 0
        return torch.tensor(board)
            
    
    def getsizeval(self, item):
        return 9, 9
    

In [3]:
trainreader = SudokuReader("randn", type="raw")
item = next(iter(trainreader))
print(item)
indices = (item['whole_sudoku'] != 0).nonzero()
print(indices)
print(torch.where(item['whole_sudoku'] != 0))
print(item['whole_sudoku'][indices[:, 0], indices[:, 1]] )

{'id': [1], 'size': (9, 9), 'whole_sudoku': tensor([[0, 7, 3, 0, 0, 0, 0, 5, 6],
        [0, 8, 0, 5, 6, 0, 3, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1],
        [7, 0, 0, 0, 8, 0, 0, 0, 0],
        [8, 0, 1, 0, 0, 6, 0, 4, 0],
        [0, 0, 0, 0, 0, 9, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 4],
        [0, 0, 0, 9, 0, 0, 0, 0, 0],
        [0, 0, 5, 6, 0, 7, 0, 0, 0]])}
tensor([[0, 1],
        [0, 2],
        [0, 7],
        [0, 8],
        [1, 1],
        [1, 3],
        [1, 4],
        [1, 6],
        [2, 8],
        [3, 0],
        [3, 4],
        [4, 0],
        [4, 2],
        [4, 5],
        [4, 7],
        [5, 5],
        [6, 8],
        [7, 3],
        [8, 2],
        [8, 3],
        [8, 5]])
(tensor([0, 0, 0, 0, 1, 1, 1, 1, 2, 3, 3, 4, 4, 4, 4, 5, 6, 7, 8, 8, 8]), tensor([1, 2, 7, 8, 1, 3, 4, 6, 8, 0, 4, 0, 2, 5, 7, 5, 8, 3, 2, 3, 5]))
tensor([7, 3, 5, 6, 8, 5, 6, 3, 1, 7, 8, 8, 1, 6, 4, 9, 4, 9, 5, 6, 7])


main.py:4: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729006826/work/torch/csrc/utils/python_arg_parser.cpp:882.)


In [4]:
from regr.graph import Graph, Concept, Relation
from regr.graph.logicalConstrain import orL, andL, existsL, notL, atLeastL, atMostL, ifL, nandL, V, exactL
from regr.graph import EnumConcept


Graph.clear()
Concept.clear()
Relation.clear()

with Graph('global') as graph:
    sudoku = Concept("sodoku")
    
#     empty_entries = Concept(name="empty_entries")
#     fixed_entries = Concept(name="fixed_entries")
    
#     (sudoku_empty, sudoku_fixed) = sudoku.has_a(empty_entries, fixed_entries)
    
    empty_entry = Concept(name='empty_entry')
    (empty_rel, ) = sudoku.contains(empty_entry)
    
#     fixed_entry = Concept(name='fixed_entry')
#     (fixed_rel, ) = fixed_entries.contains(fixed_entry)
    
    same_row = Concept(name="same_row")
#     same_row_mixed = Concept(name="same_row_mixed")
    (same_row_arg1, same_row_arg2) = same_row.has_a(arg1=empty_entry, arg2=empty_entry)
#     (same_row_mixed_arg1, same_row_mixed_arg2) = same_row_mixed.has_a(arg1=empty_entry, arg2=fixed_entry)
    
    same_col = Concept(name="same_col")
#     same_col_mixed = Concept(name="same_col_mixed")
    (same_col_arg1, same_col_arg2) = same_col.has_a(arg1=empty_entry, arg2=empty_entry)
#     (same_col_mixed_arg1, same_col_mixed_arg2) = same_col_mixed.has_a(arg1=empty_entry, arg2=fixed_entry)

    same_table = Concept(name="same_table")
    (same_table_arg1, same_table_arg2) = same_col.has_a(arg1=empty_entry, arg2=empty_entry)
    
    empty_entry_label = empty_entry(name="empty_entry_label", ConceptClass=EnumConcept, values=["v1", "v2", "v3", "v4", "v5", "v6", "v7", "v8", "v9"])


    ### Constriants
    
    for val in ["1", "2", "3", "4", "5", "6", "7", "8", "9"]:
        ### No same number in the same row between empty entries and empty entries
        ifL(getattr(empty_entry_label, f'v{val}')('x'), notL(
            existsL(
                andL(
                    same_row('z', path=("x", same_row_arg1.reversed)), getattr(empty_entry_label, f'v{val}')('y', path=("z", same_row_arg2))
                ))
        ))
        
        ### No same number in the same column between empty entries and empty entries
        ifL(getattr(empty_entry_label, f'v{val}')('x'), notL(
            existsL(
                andL(
                    same_col('z', path=("x", same_col_arg1.reversed)), getattr(empty_entry_label, f'v{val}')('y', path=("z", same_col_arg2))
                ))
        ))
        
        ### No same number in the same table between empty entries and empty entries
        ifL(getattr(empty_entry_label, f'v{val}')('x'), notL(
            existsL(
                andL(
                    same_table('z', path=("x", same_table_arg1.reversed)), getattr(empty_entry_label, f'v{val}')('y', path=("z", same_table_arg2))
                ))
        ))


Log file for dataNode is in: /home/hfaghihi/Framework/new/DomiKnowS/examples/sudoku/logs/datanode.log


main.py:26: UserWarning: Please use OrderedDict rather than dict to prevent unpredictable order of arguments.For this instance, OrderedDict([('arg1', 'empty_entry'), ('arg2', 'empty_entry')]) is used.
main.py:31: UserWarning: Please use OrderedDict rather than dict to prevent unpredictable order of arguments.For this instance, OrderedDict([('arg1', 'empty_entry'), ('arg2', 'empty_entry')]) is used.
main.py:35: UserWarning: Please use OrderedDict rather than dict to prevent unpredictable order of arguments.For this instance, OrderedDict([('arg1', 'empty_entry'), ('arg2', 'empty_entry')]) is used.


In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
class Conv2dSame(torch.nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, bias=True, padding_layer=torch.nn.ReflectionPad2d):
        """It only support square kernels and stride=1, dilation=1, groups=1."""
        super(Conv2dSame, self).__init__()
        ka = kernel_size // 2
        kb = ka - 1 if kernel_size % 2 == 0 else ka
        self.net = nn.Sequential(
            padding_layer((ka,kb,ka,kb)),
            nn.Conv2d(in_channels, out_channels, kernel_size, bias=bias),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(True)
        )
    def forward(self, x):
        return self.net(x)
class SudokuCNN(nn.Module):
    def __init__(self):
        super(SudokuCNN, self).__init__()
        self.conv_layers = nn.Sequential(Conv2dSame(1,512,3), #1
                                         Conv2dSame(512,512,3),#2
                                         Conv2dSame(512,512,3),#3
                                         Conv2dSame(512,512,3),#4
                                         Conv2dSame(512,512,3),#5
                                         Conv2dSame(512,512,3),#6
                                         Conv2dSame(512,512,3),#7
                                         Conv2dSame(512,512,3),#8
                                         Conv2dSame(512,512,3),#9
                                         Conv2dSame(512,512,3),#10
                                         Conv2dSame(512,512,3),#11
                                         Conv2dSame(512,512,3),#12
                                         Conv2dSame(512,512,3),#13
                                         Conv2dSame(512,512,3),#14
                                         Conv2dSame(512,512,3))#15
        self.last_conv = nn.Conv2d(512, 9, 1)
    def forward(self, x):
        x = self.conv_layers(x)
        x = self.last_conv(x)
        x = x.permute(0,2,3,1)
        return x

In [6]:
from regr.sensor.pytorch.sensors import FunctionalSensor, JointSensor, ReaderSensor, FunctionalReaderSensor
from regr.sensor.pytorch.learners import ModuleLearner
from regr.sensor.pytorch.relation_sensors import CompositionCandidateSensor
from regr.sensor.pytorch.query_sensor import DataNodeReaderSensor

class JointFunctionalReaderSensor(JointSensor, FunctionalReaderSensor):
    pass


# def getempties(*prev, data):
#     rows, cols = torch.where(data == 0)
#     rel = torch.ones(1, 1)
#     return [rows], [cols]
    
def getfixed(*prev, data):
    rows, cols = torch.where(data != 0)
    fix = torch.zeros(data.shape)
    vals = torch.ones(data.shape) * -1
    for i, j in zip(rows.detach().tolist(), cols.detach().tolist()):
        fix[i][j] = 1
        vals[i][j] = data[i][j]
        
        
    return fix.reshape(fix.shape[0]*fix.shape[1]), vals.reshape(vals.shape[0]*vals.shape[1])

def makeSoduko(*prev, data):
    num_rows = data[0]
    num_cols = data[1]
    rows = torch.arange(num_rows).unsqueeze(-1)
    rows = rows.repeat(1,num_cols).reshape(num_rows*num_cols)
    
    cols = torch.arange(num_rows)
    cols = cols.unsqueeze(0).repeat(num_rows, 1).reshape(num_rows*num_cols)
    
    rel = torch.ones(data[0]*data[1], 1)
    
    return rows, cols, rel

def getlabel(*prev, data):
    rows, cols = torch.where(data != 0)
    vals = torch.ones(data.shape) * -100
    for i, j in zip(rows.detach().tolist(), cols.detach().tolist()):
        vals[i][j] = data[i][j] - 1
        
        
    return vals.reshape(vals.shape[0]*vals.shape[1])
    
    
def createSudoku(*prev, data):
    return [1]

sudoku['index'] = FunctionalReaderSensor(keyword='size', forward=createSudoku)
    
empty_entry['rows', 'cols', empty_rel] = JointFunctionalReaderSensor(sudoku['index'], keyword='size', forward=makeSoduko)
empty_entry['fixed', 'val'] = JointFunctionalReaderSensor('rows', 'cols', empty_rel, keyword='whole_sudoku', forward=getfixed)

class FunctionalModuleLearner(ModuleLearner):
    def forward(self, *inputs):
        inputs = list(inputs)
        inputs[0] = inputs[0].view(1, 1,9, 9)
        return self.module(*inputs)

empty_entry[empty_entry_label] = FunctionalModuleLearner('val', module=SudokuCNN())
empty_entry[empty_entry_label] = FunctionalReaderSensor(keyword='whole_sudoku', label=True, forward=getlabel)
# fixed_entries['rows1', 'cols'] = JointFunctionalReaderSensor(keyword='whole_sudoku', forward=getfixed)


### What kind of model should we use for learning the entries? Because it should be aware of all other decision to make the correct decision, otherwise it is impossible for the model to learn good weights.




In [11]:
from regr.program import POIProgram, SolverPOIProgram, IMLProgram, CallbackProgram
from regr.program.callbackprogram import ProgramStorageCallback
from regr.program.metric import MacroAverageTracker, PRF1Tracker, DatanodeCMMetric
from regr.program.loss import NBCrossEntropyLoss, NBCrossEntropyIMLoss

program = SolverPOIProgram(
        graph, poi=(sudoku, empty_entry, ), inferTypes=['local/argmax'],
        loss=MacroAverageTracker(NBCrossEntropyLoss()),
        metric={
            'argmax': PRF1Tracker(DatanodeCMMetric('local/argmax'))})

In [12]:
for datanode in program.populate(trainreader):
    print(datanode)
    
    print(datanode.getChildDataNodes(conceptName=empty_entry))

sodoku 0
[empty_entry 0, empty_entry 1, empty_entry 2, empty_entry 3, empty_entry 4, empty_entry 5, empty_entry 6, empty_entry 7, empty_entry 8, empty_entry 9, empty_entry 10, empty_entry 11, empty_entry 12, empty_entry 13, empty_entry 14, empty_entry 15, empty_entry 16, empty_entry 17, empty_entry 18, empty_entry 19, empty_entry 20, empty_entry 21, empty_entry 22, empty_entry 23, empty_entry 24, empty_entry 25, empty_entry 26, empty_entry 27, empty_entry 28, empty_entry 29, empty_entry 30, empty_entry 31, empty_entry 32, empty_entry 33, empty_entry 34, empty_entry 35, empty_entry 36, empty_entry 37, empty_entry 38, empty_entry 39, empty_entry 40, empty_entry 41, empty_entry 42, empty_entry 43, empty_entry 44, empty_entry 45, empty_entry 46, empty_entry 47, empty_entry 48, empty_entry 49, empty_entry 50, empty_entry 51, empty_entry 52, empty_entry 53, empty_entry 54, empty_entry 55, empty_entry 56, empty_entry 57, empty_entry 58, empty_entry 59, empty_entry 60, empty_entry 61, empty_en