In [1]:
import torch
import json

In [2]:
import os
print(os.getcwd())
# Please change the root to an absolute or relative path to DomiKnowS root.
# In case relative path is used, consider the printed `CWD` as current working directory.
root = '/home/hfaghihi/Framework/DomiKnowS'
import sys
sys.path.append(root)
from typing import Any, Dict

/home/hfaghihi/Framework/DomiKnowS/examples/Propara


In [3]:
with open("updated_test_data.json", "r") as file:
    data = json.load(file)
data[2]

{'id': '37',
 'entities': ['bones'],
 'steps': ['A plant of animal dies in a watery environment.',
  'Is buried in mud and silt.',
  'Soft tissues quickly decompose leaving behind hard bones or shells.',
  'Over time sediment builds over the top and hardens into rock.',
  'As the bone decays mineral seeps in replacing it.',
  'Fossils are formed.'],
 'entity_step': [[0.005079575348645449,
   0.003536409232765436,
   0.9913840293884277],
  [0.0023296682629734278, 0.002440220210701227, 0.9952301979064941],
  [0.004893037490546703, 0.004029534757137299, 0.9910774230957031],
  [0.9432244300842285, 0.05380963161587715, 0.002965932944789529],
  [0.9029137492179871, 0.09116195142269135, 0.005924322176724672],
  [0.005038038361817598, 0.008660664781928062, 0.9863013029098511],
  [0.006529272999614477, 0.009216826409101486, 0.9842538833618164]]}

In [4]:
from regr.data.reader import RegrReader

In [5]:
class ProparaReader(RegrReader):
    def getprocedureIDval(self, item):
        return [item['id']]
    def getentitiesval(self, item):
        return item['entities']
    def getstepsval(self, item):
        num_steps = len(item['steps']) + 1
        rel = torch.ones(num_steps,1)
        sentences = ["step 0 information"]
        sentences.extend(item['steps'])
        return rel, sentences
    
    def getnon_existenceval(self, item):
        values = []
        for step in range(len(item['steps']) + 1):
            values.append([1 - item['entity_step'][step][2], item['entity_step'][step][2]])
        return torch.tensor(values)
            
    def getknownval(self, item):
        values = []
        for step in range(len(item['steps']) + 1):
            values.append([1 - item['entity_step'][step][0], item['entity_step'][step][0]])
        return torch.tensor(values)
    
    def getunknownval(self, item):
        values = []
        for step in range(len(item['steps']) + 1):
            values.append([1 - item['entity_step'][step][1], item['entity_step'][step][1]])
        return torch.tensor(values)
    
    def getactionval(self, item):
        action1s = torch.diag(torch.ones(len(item['steps']) + 1) )[:-1]
        action2s = torch.diag(torch.ones(len(item['steps']) + 1) )[1:]
        raw = torch.zeros(len(item['steps']))
        return action1s, action2s
    
    def getcreateval(self, item):
        actions = []
        prev_state = item['entity_step'][0]
        for sid, step in enumerate(item['steps']):
            o = 0
            c = 0
            d = 0
            o += (prev_state[0] * item['entity_step'][sid+1][0])
            o += (prev_state[0] * item['entity_step'][sid+1][1])
            o += (prev_state[1] * item['entity_step'][sid+1][0])
            o += (prev_state[1] * item['entity_step'][sid+1][1])
            o += (prev_state[2] * item['entity_step'][sid+1][2])
            d += (prev_state[0] * item['entity_step'][sid+1][2])
            d += (prev_state[1] * item['entity_step'][sid+1][2])
            c += (prev_state[2] * item['entity_step'][sid+1][1])
            c += (prev_state[2] * item['entity_step'][sid+1][0])
            actions.append([1-c, c])
            prev_state = item['entity_step'][sid+1]
        
        return torch.tensor(actions)
                    
    def getdestroyval(self, item):
        actions = []
        prev_state = item['entity_step'][0]
        for sid, step in enumerate(item['steps']):
            o = 0
            c = 0
            d = 0
            o += (prev_state[0] * item['entity_step'][sid+1][0])
            o += (prev_state[0] * item['entity_step'][sid+1][1])
            o += (prev_state[1] * item['entity_step'][sid+1][0])
            o += (prev_state[1] * item['entity_step'][sid+1][1])
            o += (prev_state[2] * item['entity_step'][sid+1][2])
            d += (prev_state[0] * item['entity_step'][sid+1][2])
            d += (prev_state[1] * item['entity_step'][sid+1][2])
            c += (prev_state[2] * item['entity_step'][sid+1][1])
            c += (prev_state[2] * item['entity_step'][sid+1][0])
            actions.append([1-d, d])
            prev_state = item['entity_step'][sid+1]
        return torch.tensor(actions)
    
    def getotherval(self, item):
        actions = []
        prev_state = item['entity_step'][0]
        for sid, step in enumerate(item['steps']):
            o = 0
            c = 0
            d = 0
            o += (prev_state[0] * item['entity_step'][sid+1][0])
            o += (prev_state[0] * item['entity_step'][sid+1][1])
            o += (prev_state[1] * item['entity_step'][sid+1][0])
            o += (prev_state[1] * item['entity_step'][sid+1][1])
            o += (prev_state[2] * item['entity_step'][sid+1][2])
            d += (prev_state[0] * item['entity_step'][sid+1][2])
            d += (prev_state[1] * item['entity_step'][sid+1][2])
            c += (prev_state[2] * item['entity_step'][sid+1][1])
            c += (prev_state[2] * item['entity_step'][sid+1][0])
            actions.append([1-o, o])
            prev_state = item['entity_step'][sid+1]
        return torch.tensor(actions)
    
    def getbeforeval(self, item):
        b1s = []
        b2s = []
        for step in range(len(item['steps']) + 1):
            b1 = torch.zeros(len(item['steps']) + 1)
            b1[step] = 1
            for step1 in range(len(item['steps']) + 1):
                b2 = torch.zeros(len(item['steps']) + 1)
                b2[step1] = 1
                b1s.append(b1)
                b2s.append(b2)
        return torch.stack(b1s), torch.stack(b2s)
    
    def getbefore_trueval(self, item):
        num_steps = len(item['steps']) + 1
        values = torch.zeros(num_steps * num_steps)
        for step in range(len(item['steps']) + 1):
            for step1 in range(step + 1, len(item['steps']) + 1):
                values[(step*num_steps)+step1] = 1
        return values
    

In [6]:
ReaderObjectsIterator = ProparaReader("updated_test_data.json")
list(iter(ReaderObjectsIterator))[2]

{'action': (tensor([[1., 0., 0., 0., 0., 0., 0.],
          [0., 1., 0., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]]),
  tensor([[0., 1., 0., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 0., 0., 1.]])),
 'before_true': tensor([0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
         1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
         0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 'before': (tensor([[1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 

In [20]:
from regr.graph import Graph, Concept, Relation
from regr.graph.logicalConstrain import orL, andL, existsL, notL, atLeastL, atMostL, ifL, nandL, eqL

Graph.clear()
Concept.clear()
Relation.clear()

with Graph('global') as graph:
    procedure = Concept("procedure")
    step = Concept("step")
    (procedure_contain_step, ) = procedure.contains(step)
#     entity = Concept("entity")
    non_existence = step("non_existence")
    unknown_loc = step("unknown_location")
    known_loc = step("known_location")
    before = Concept("before")
    (before_arg1, before_arg2) = before.has_a(arg1=step, arg2=step)
    action = Concept("action")
    (action_arg1, action_arg2) = action.has_a(arg1=step, arg2=step)
    create = action(name="create")
    destroy = action(name="destroy")
    other = action(name="other")
    
    #LC5 : If action is create then the first step should be non_existence and the second step can be either known_loc or unknown_loc
    ifL(create, ("x", "y", ), andL(non_existence, ("x", ), orL(known_loc, ("y", ), unknown_loc, ("y", ))))
    
    #LC 6 : If action is destroy, then first step should be either known_loc,or unknown_loc and the next step should be non_existence 
    ifL(destroy, ("x", "y", ), andL(orL(known_loc, ("x", ), unknown_loc, ("x", )), non_existence, ("y", )))
    
    #LC7 : There should be at most 1 create
    atMostL(1, ("x", ), create, ("x", ))
    
    #LC8 : There should be at most one destroy
    atMostL(1, ("x", ), destroy, ("x", ))
    
    #LC9 : If (x1,x2) is create and (y1, y2) is destroy, then the pair(x2,y2) in before should have the property "check" equal to 1.
    # I will have to check if this eqL works if not will update it
    ifL(andL(create, ("x1", "x2"), destroy, ("y1", "y2")), eqL(before, "check", 1), ("x2", "y2"))
    
    #LC1 : An action can not be create, destroy and other at the same time
    nandL(create, destroy, other)
    
    #LC2 : An action should at least be one of the create, destroy or other
    orL(create, destroy, other)
    
    #LC3 : A step can not be known_loc, unknown_loc and non_existence at the same time
    nandL(known_loc, unknown_loc, non_existence)
    
    #LC4 : A step should at least be one of known_loc, unknown_loc or non_existence
    orL(known_loc, unknown_loc, non_existence)
    




/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:17: UserWarning: Please use OrderedDict rather than dict to prevent unpredictable order of arguments.For this instance, OrderedDict([('arg1', 'step'), ('arg2', 'step')]) is used.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:19: UserWarning: Please use OrderedDict rather than dict to prevent unpredictable order of arguments.For this instance, OrderedDict([('arg1', 'step'), ('arg2', 'step')]) is used.


In [21]:
from regr.sensor.pytorch.sensors import ReaderSensor, JointSensor
from regr.sensor.pytorch.relation_sensors import EdgeSensor

class EdgeReaderSensor(EdgeSensor, ReaderSensor):
    def __init__(self, *pres, relation, mode="forward", keyword=None, **kwargs):
        super().__init__(*pres, relation=relation, mode=mode, **kwargs)
        self.keyword = keyword
        self.data = None
        
# class JoinReaderSensor(JointSensor, ReaderSensor):
#     pass
            
# class JoinEdgeReaderSensor(JointSensor, EdgeReaderSensor):
#     pass

class JoinReaderSensor(JointSensor, ReaderSensor):
    pass

class JoinEdgeReaderSensor(JoinReaderSensor, EdgeSensor):
    pass

In [22]:
from regr.sensor.pytorch.sensors import ReaderSensor
from regr.program import LearningBasedProgram
from regr.program.model.pytorch import PoiModel
import torch
from torch import nn

def model_declaration():

    graph.detach()

    # --- City
    procedure['id'] = ReaderSensor(keyword='procedureID')
    step[procedure_contain_step.forward, 'text'] = JoinReaderSensor(procedure['id'], keyword='steps')
    # word[step_contains_word, 'raw'] = ReaderSensor(keyword='words')
#     entity['raw'] = ReaderSensor(keyword='entities')

    step[non_existence] = ReaderSensor(procedure_contain_step.forward, 'text', keyword='non_existence')
    step[unknown_loc] = ReaderSensor(procedure_contain_step.forward, 'text', keyword='unknown')
    step[known_loc] = ReaderSensor(procedure_contain_step.forward, 'text', keyword='known')
    
    step[non_existence] = ReaderSensor(keyword='non_existence', label=True)
    step[unknown_loc] = ReaderSensor(keyword='unknown', label=True)
    step[known_loc] = ReaderSensor(keyword='known', label=True)
    
    action[action_arg1.backward, action_arg2.backward] = JoinReaderSensor(step['text'], keyword='action')
    
    action[create] = ReaderSensor(action_arg1.backward, action_arg2.backward, keyword='create')
    action[destroy] = ReaderSensor(action_arg1.backward, action_arg2.backward, keyword='destroy')
    action[other] = ReaderSensor(action_arg1.backward, action_arg2.backward, keyword='other')
    
    action[create] = ReaderSensor(keyword='create', label=True)
    action[destroy] = ReaderSensor(keyword='destroy', label=True)
    action[other] = ReaderSensor(keyword='other', label=True)
    
    before[before_arg1.backward, before_arg2.backward] = JoinReaderSensor(step['text'], keyword="before")
    
    before["check"] = ReaderSensor(before_arg1.backward, before_arg2.backward, keyword="before_true")
    before["check"] = ReaderSensor(keyword="before_true", label=True)
    
    program = LearningBasedProgram(graph, **{
        'Model': PoiModel,
#         'poi': (known_loc, unknown_loc, non_existence, other, destroy, create),
        'loss': None,
        'metric': None,
    })
    return program

In [23]:
def main():
    # set logger level to see training and testing logs
    import logging
    logging.basicConfig(level=logging.INFO)

    lbp = model_declaration()

    dataset = ProparaReader(file='updated_test_data.json')  # Adding the info on the reader

#     lbp.test(dataset, device='auto')
    all_updates = []
    for datanode in lbp.populate(dataset, device="cpu"):
#         print('datanode:', datanode)
        datanode.inferILPConstrains(create, destroy, other, non_existence, known_loc, unknown_loc, fun=None)
        final_output = {"id": datanode.getAttribute('id'), "steps":[], "actions":[], "steps_before": [], "actions_before": []}
        for step_info in datanode.findDatanodes(select = step):
            k = step_info.getAttribute(known_loc, "ILP")
            u = step_info.getAttribute(unknown_loc, "ILP")
            n = step_info.getAttribute(non_existence, "ILP")
            final_output["steps"].append((k,u,n))
            k = step_info.getAttribute(known_loc)
            u = step_info.getAttribute(unknown_loc)
            n = step_info.getAttribute(non_existence)
            final_output["steps_before"].append((k,u,n))
        for action_info in datanode.findDatanodes(select = action):
            c = action_info.getAttribute(create, "ILP")
            d = action_info.getAttribute(destroy, "ILP")
            o = action_info.getAttribute(other, "ILP")
            final_output["actions"].append((c,d,o))
            c = action_info.getAttribute(create)
            d = action_info.getAttribute(destroy)
            o = action_info.getAttribute(other)
            final_output["actions_before"].append((c,d,o))
        all_updates.append(final_output)
#         print('datanode:', datanode)
#         print('inference spam:', datanode.getAttribute(Spam, 'ILP'))
#         print('inference regular:', datanode.getAttribute(Regular, 'ILP'))
    print(len(all_updates))
    return all_updates

In [24]:
fdata = main()

236


In [27]:
fdata[2]
# dataset = ProparaReader(file='updated_test_data.json')  # Adding the info on the reader
# print(list(iter(dataset))[2]['non_existence'])

{'id': '37',
 'steps': [(tensor([1.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([1.], device='cuda:0', dtype=torch.float64)),
  (tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([1.], device='cuda:0', dtype=torch.float64),
   tensor([1.], device='cuda:0', dtype=torch.float64)),
  (tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([1.], device='cuda:0', dtype=torch.float64)),
  (tensor([1.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64)),
  (tensor([1.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64)),
  (tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([1.], device='cuda:0', dtype

In [46]:
from regr.graph import DataNodeBuilder
from regr.sensor.sensor import Sensor
import logging
logging.basicConfig(level=logging.INFO)

lbp = model_declaration()
dataset = ProparaReader(file='updated_test_data.json')
for datanode in lbp.populate(list(dataset)[0:1], device="cpu"):
    pass
dataset = ProparaReader(file='updated_test_data.json')
all_updates = []
for data in list(iter(dataset)):
    context = {"graph": graph}
    context.update(data)
    data_item = DataNodeBuilder(context)
    # data_item
    for sensor in procedure['id'].find(Sensor):
        sensor(data_item)
    for sensor in step['text'].find(Sensor):
        sensor(data_item)
    for sensor in step[procedure_contain_step.forward].find(Sensor):
        sensor(data_item)
    for sensor in step[known_loc].find(Sensor):
        sensor(data_item)
    for sensor in step[unknown_loc].find(Sensor):
        sensor(data_item)
    for sensor in step[non_existence].find(Sensor):
        sensor(data_item)
    for sensor in action[action_arg1.backward].find(Sensor):
        sensor(data_item)
    for sensor in action[action_arg2.backward].find(Sensor):
        sensor(data_item)
    for sensor in action[destroy].find(Sensor):
        sensor(data_item)
    for sensor in action[create].find(Sensor):
        sensor(data_item)
    for sensor in action[other].find(Sensor):
        sensor(data_item)
        
    datanode = data_item.getDataNode()
    datanode.inferILPConstrains(create, destroy, other, non_existence, known_loc, unknown_loc, fun=None)
    final_output = {"id": datanode.getAttribute('id'), "entities": data_item['entities'], "steps":[], "actions":[], "steps_before": [], "actions_before": []}
    for step_info in datanode.findDatanodes(select = step):
        k = step_info.getAttribute(known_loc, "ILP")
        u = step_info.getAttribute(unknown_loc, "ILP")
        n = step_info.getAttribute(non_existence, "ILP")
        final_output["steps"].append((k,u,n))
        k = step_info.getAttribute(known_loc)
        u = step_info.getAttribute(unknown_loc)
        n = step_info.getAttribute(non_existence)
        final_output["steps_before"].append((k,u,n))
    for action_info in datanode.findDatanodes(select = action):
        c = action_info.getAttribute(create, "ILP")
        d = action_info.getAttribute(destroy, "ILP")
        o = action_info.getAttribute(other, "ILP")
        final_output["actions"].append((c,d,o))
        c = action_info.getAttribute(create)
        d = action_info.getAttribute(destroy)
        o = action_info.getAttribute(other)
        final_output["actions_before"].append((c,d,o))
    all_updates.append(final_output)

In [47]:
all_updates[2]

{'id': '37',
 'entities': ['bones'],
 'steps': [(tensor([1.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64)),
  (tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([1.], device='cuda:0', dtype=torch.float64)),
  (tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([1.], device='cuda:0', dtype=torch.float64)),
  (tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([1.], device='cuda:0', dtype=torch.float64)),
  (tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([1.], device='cuda:0', dtype=torch.float64)),
  (tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([0.], device='cuda:0', dtype=torch.float64),
   tensor([1.]

In [59]:
context = {"graph": graph}
context.update(list(iter(dataset))[2])
data_item = DataNodeBuilder(context)
# data_item
for sensor in procedure['id'].find(Sensor):
    sensor(data_item)
for sensor in step['text'].find(Sensor):
    sensor(data_item)
for sensor in step[procedure_contain_step.forward].find(Sensor):
    sensor(data_item)
for sensor in step[known_loc].find(Sensor):
    sensor(data_item)
for sensor in step[unknown_loc].find(Sensor):
    sensor(data_item)
for sensor in step[non_existence].find(Sensor):
    sensor1 = sensor
    sensor(data_item)
for sensor in action[action_arg1.backward].find(Sensor):
    sensor(data_item)
for sensor in action[action_arg2.backward].find(Sensor):
    sensor(data_item)
for sensor in action[destroy].find(Sensor):
    sensor(data_item)
for sensor in action[create].find(Sensor):
    sensor(data_item)
for sensor in action[other].find(Sensor):
    sensor(data_item)
print(data_item[sensor1])
print(list(iter(dataset))[2]['non_existence'])
datanode = data_item.getDataNode()
print(datanode.findDatanodes(select=step)[1].getAttribute('non_existence'))

tensor([[0.9976, 0.0024],
        [0.0150, 0.9850],
        [0.0084, 0.9916],
        [0.0046, 0.9954],
        [0.0042, 0.9958],
        [0.0043, 0.9957],
        [0.0049, 0.9951]])
tensor([[0.0086, 0.9914],
        [0.0048, 0.9952],
        [0.0089, 0.9911],
        [0.9970, 0.0030],
        [0.9941, 0.0059],
        [0.0137, 0.9863],
        [0.0157, 0.9843]])
tensor([0.0150, 0.9850])


In [56]:
data_item

{'graph': Graph(name='global', fullname='global'),
 'action': (tensor([[1., 0., 0., 0., 0., 0., 0.],
          [0., 1., 0., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]]),
  tensor([[0., 1., 0., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 0., 0., 1.]])),
 'before_true': tensor([0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
         1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
         0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 'before': (tensor([[1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
    

In [52]:
list(iter(dataset))[2]

{'action': (tensor([[1., 0., 0., 0., 0., 0., 0.],
          [0., 1., 0., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]]),
  tensor([[0., 1., 0., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 0., 0., 1.]])),
 'before_true': tensor([0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
         1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
         0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 'before': (tensor([[1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [1., 